<?xml version="1.0" encoding="utf-8"?><Database Name="GDUmanagement" Class="GDUDataConnectionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OO562L9;Initial Catalog=GDUmanagement;Persist Security Info=True;User ID=hieu99" SettingsObjectName="GDU_Management.Properties.Settings" SettingsPropertyName="GDUmanagementConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="MaAdmin" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenAdmin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThoiKhoaBieu" Member="ThoiKhoaBieus">
    <Type Name="ThoiKhoaBieu">
      <Column Name="MaTKB" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HocKi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngayhoc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayKetthuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhongHoc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="GiangVien_ThoiKhoaBieu" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="Lop_ThoiKhoaBieu" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
      <Association Name="MonHoc_ThoiKhoaBieu" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiemMonHoc" Member="DiemMonHocs">
    <Type Name="DiemMonHoc">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem30" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diem70L1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diem70L2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DTB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemChu" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="MonHoc_DiemMonHoc" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
      <Association Name="SinhVien_DiemMonHoc" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MaGV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="GiangVien_ThoiKhoaBieu" Member="ThoiKhoaBieus" ThisKey="MaGV" OtherKey="MaGV" Type="ThoiKhoaBieu" />
    </Type>
  </Table>
  <Table Name="dbo.Khoa" Member="Khoas">
    <Type Name="Khoa">
      <Column Name="MaKhoa" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Khoa_NganhHoc" Member="NganhHocs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="NganhHoc" />
    </Type>
  </Table>
  <Table Name="dbo.KhoaHoc" Member="KhoaHocs">
    <Type Name="KhoaHoc">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NienKhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KhoaHoc_Lop" Member="Lops" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Lop_ThoiKhoaBieu" Member="ThoiKhoaBieus" ThisKey="MaLop" OtherKey="MaLop" Type="ThoiKhoaBieu" />
      <Association Name="Lop_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
      <Association Name="KhoaHoc_Lop" Member="KhoaHoc" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="KhoaHoc" IsForeignKey="true" />
      <Association Name="NganhHoc_Lop" Member="NganhHoc" ThisKey="MaNganh" OtherKey="MaNganh" Type="NganhHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="STC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="MonHoc_ThoiKhoaBieu" Member="ThoiKhoaBieus" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="ThoiKhoaBieu" />
      <Association Name="MonHoc_DiemMonHoc" Member="DiemMonHocs" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="DiemMonHoc" />
      <Association Name="NganhHoc_MonHoc" Member="NganhHoc" ThisKey="MaNganh" OtherKey="MaNganh" Type="NganhHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NganhHoc" Member="NganhHocs">
    <Type Name="NganhHoc">
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NganhHoc_Lop" Member="Lops" ThisKey="MaNganh" OtherKey="MaNganh" Type="Lop" />
      <Association Name="NganhHoc_MonHoc" Member="MonHocs" ThisKey="MaNganh" OtherKey="MaNganh" Type="MonHoc" />
      <Association Name="Khoa_NganhHoc" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="SinhVien_DiemMonHoc" Member="DiemMonHocs" ThisKey="MaSV" OtherKey="MaSV" Type="DiemMonHoc" />
      <Association Name="Lop_SinhVien" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
</Database>